#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

PUBLISH_MODE="${PALM_OIL_PUBLISH_MODE:-git}"
REPORT_DATA_MODE="${PALM_OIL_REPORT_DATA_MODE:-refresh}"
TARGET_REPORT="${PALM_OIL_TARGET_REPORT:-}"
case "$PUBLISH_MODE" in
  git|files) ;;
  *)
    echo "PALM_OIL_PUBLISH_MODE must be git or files" >&2
    exit 2
    ;;
esac
case "$REPORT_DATA_MODE" in
  refresh|prepared) ;;
  *)
    echo "PALM_OIL_REPORT_DATA_MODE must be refresh or prepared" >&2
    exit 2
    ;;
esac

changed_reports=()
while IFS= read -r report_path; do
  changed_reports+=("$report_path")
done < <(
  {
    git diff --name-only -- 'reports/*.md'
    git diff --cached --name-only -- 'reports/*.md'
    git ls-files --others --exclude-standard -- 'reports/*.md'
  } | sort -u
)

if [[ -n "$TARGET_REPORT" ]]; then
  if [[ ! "$TARGET_REPORT" =~ ^reports/[0-9]{4}-[0-9]{2}-[0-9]{2}(-weekend)?\.md$ ]]; then
    echo "PALM_OIL_TARGET_REPORT must be one dated report path" >&2
    exit 2
  fi
  target_changed=false
  for report_path in "${changed_reports[@]}"; do
    if [[ "$report_path" == "$TARGET_REPORT" ]]; then
      target_changed=true
      break
    fi
  done
  if [[ "$target_changed" != true ]]; then
    echo "target report is not present in the changed report set: $TARGET_REPORT" >&2
    exit 2
  fi
  # The server runtime restores previously published Markdown so the report
  # index can be rebuilt. Those historical files may not have a matching
  # source_runs directory in the fresh runtime and must not be mistaken for
  # reports generated by this invocation. The explicitly selected target
  # remains subject to every title, data, forecast and report-quality gate.
  changed_reports=("$TARGET_REPORT")
fi

daily_report_dates=()
for report_path in "${changed_reports[@]}"; do
  report_file="$(basename "$report_path")"
  if [[ "$report_file" != *-weekend.md ]]; then
    report_date="${report_file%.md}"
    if [[ ! "$report_date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
      echo "invalid daily report filename: $report_path" >&2
      exit 2
    fi
    daily_report_dates+=("$report_date")
  fi
done

unique_daily_dates=()
while IFS= read -r report_date; do
  [[ -n "$report_date" ]] && unique_daily_dates+=("$report_date")
done < <(printf '%s\n' "${daily_report_dates[@]}" | sort -u)

if (( ${#unique_daily_dates[@]} > 1 )); then
  echo "multiple daily report dates detected; refusing to bind one market snapshot to multiple forecasts" >&2
  exit 2
fi

if (( ${#changed_reports[@]} > 0 )); then
  python3 scripts/check_title_quality.py "${changed_reports[@]}"
fi

for report_path in "${changed_reports[@]}"; do
  report_file="$(basename "$report_path")"
  if [[ "$report_file" == *-weekend.md ]]; then
    report_date="${report_file%-weekend.md}"
    report_kind="weekend"
    run_dir="source_runs/${report_date}-weekend"
    manifest="${run_dir}/manifest.json"
    source_json="${run_dir}/raw/futures_market_data.weekly_compatible.json"
    if [[ ! -f "$source_json" ]]; then
      source_json="${run_dir}/raw/futures_market_data.json"
    fi
  else
    report_date="${report_file%.md}"
    report_kind="daily"
    run_dir="source_runs/${report_date}-daily"
    manifest="${run_dir}/manifest.json"
    source_json="${run_dir}/raw/futures_market_data.json"
  fi
  python3 skills/data_quality_gate_skill/scripts/validate_data.py --manifest "$manifest" --strict
  if [[ "$report_file" != *-weekend.md ]]; then
    python3 skills/forecast_tracking_skill/scripts/validate_report_feedback.py \
      --report "$report_path" \
      --feedback data/forecast/feedback/latest.json \
      --report-date "$report_date"
  fi
  report_audit=(
    python3 skills/report_writer_skill/scripts/audit_report.py
    --report "$report_path"
    --outline "${run_dir}/report_outline.json"
    --kind "$report_kind"
    --source-json "$source_json"
    --output "${run_dir}/report_quality.json"
    --min-score 92
  )
  if [[ "$report_kind" == "daily" ]]; then
    report_audit+=(--feedback data/forecast/feedback/latest.json)
  fi
  "${report_audit[@]}"
done

update_oil_futures_tab=false
for report_path in "${changed_reports[@]}"; do
  if [[ "$report_path" != *-weekend.md ]]; then
    update_oil_futures_tab=true
    break
  fi
done

if [[ "$update_oil_futures_tab" == true && "$REPORT_DATA_MODE" == "refresh" ]]; then
  report_date="${unique_daily_dates[0]}"
  time_metadata="$({ python3 scripts/update_oil_futures_data.py \
    --report-date "$report_date" \
    --print-time-metadata; } 2>&1)" || {
      echo "$time_metadata" >&2
      exit 2
    }
  generated_at="$(printf '%s' "$time_metadata" | python3 -c 'import json,sys; print(json.load(sys.stdin)["generated_at"])')"
  cutoff_at="$(printf '%s' "$time_metadata" | python3 -c 'import json,sys; print(json.load(sys.stdin)["cutoff_at"])')"
  python3 scripts/update_oil_futures_data.py \
    --report-date "$report_date" \
    --generated-at "$generated_at" \
    --cutoff-at "$cutoff_at" \
    --update-session morning
  python3 skills/data_quality_gate_skill/scripts/validate_data.py --oil-futures data/oil_futures.js --strict
elif [[ "$update_oil_futures_tab" == true ]]; then
  echo "use prepared server-owned market datasets for daily report deploy"
  python3 skills/data_quality_gate_skill/scripts/validate_data.py --oil-futures data/oil_futures.js --strict
  python3 server/freeze_prepared_forecast.py \
    --report-date "$report_date" \
    --oil-futures data/oil_futures.js
else
  echo "skip oil futures tab update for weekly-only report deploy"
fi

python3 scripts/publish_report.py

if git diff --quiet -- reports data downloads; then
  echo "no report changes to deploy"
  exit 0
fi

if [[ "$PUBLISH_MODE" == "files" ]]; then
  python3 - "$REPORT_DATA_MODE" <<'PY'
import json
import sys

print(json.dumps({
    "status": "ok",
    "publish_mode": "files",
    "report_data_mode": sys.argv[1],
}, ensure_ascii=False, sort_keys=True))
PY
  exit 0
fi

# Stage only website and mini-program artifacts.  Do not add the whole data
# directory: report publication also creates ignored runtime snapshots, and an
# explicit directory add exits non-zero before the exclusion pathspec applies.
git add -- reports downloads miniprogram/data \
  data/contracts \
  data/report_quality \
  data/oil_futures.js data/oil_futures.json \
  data/reports.js data/reports.json data/version.js
if git diff --cached --name-only -- data/forecast/daily data/review/runtime_snapshots | grep -q .; then
  echo "refusing to publish Git-ignored forecast or runtime snapshot artifacts" >&2
  exit 2
fi
git commit -m "Update palm oil report"
python3 scripts/sync_automation_runtime.py --root "$PWD"
